// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRYXDbWcNAM4S3jxixlvnLnKegqQBxUW4',
    appId: '1:398456425469:web:72faa4ec2f0370716e2794',
    messagingSenderId: '398456425469',
    projectId: 'lexiguard-32c63',
    authDomain: 'lexiguard-32c63.firebaseapp.com',
    databaseURL: 'https://lexiguard-32c63-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lexiguard-32c63.firebasestorage.app',
    measurementId: 'G-3EF9DQ4MEB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxNyFEkZIyKTOIZdDG5gLONvIo3RwHKP8',
    appId: '1:398456425469:ios:6580b1dc03c52ebc6e2794',
    messagingSenderId: '398456425469',
    projectId: 'lexiguard-32c63',
    databaseURL: 'https://lexiguard-32c63-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lexiguard-32c63.firebasestorage.app',
    androidClientId: '398456425469-273514f2iqraccp3vrjuhr4v8vfg5430.apps.googleusercontent.com',
    iosClientId: '398456425469-v4060i1mchj507fsvtogllok79pkvn6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.leiGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxNyFEkZIyKTOIZdDG5gLONvIo3RwHKP8',
    appId: '1:398456425469:ios:6580b1dc03c52ebc6e2794',
    messagingSenderId: '398456425469',
    projectId: 'lexiguard-32c63',
    databaseURL: 'https://lexiguard-32c63-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lexiguard-32c63.firebasestorage.app',
    androidClientId: '398456425469-273514f2iqraccp3vrjuhr4v8vfg5430.apps.googleusercontent.com',
    iosClientId: '398456425469-v4060i1mchj507fsvtogllok79pkvn6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.leiGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRYXDbWcNAM4S3jxixlvnLnKegqQBxUW4',
    appId: '1:398456425469:web:93a341cab73cdd946e2794',
    messagingSenderId: '398456425469',
    projectId: 'lexiguard-32c63',
    authDomain: 'lexiguard-32c63.firebaseapp.com',
    databaseURL: 'https://lexiguard-32c63-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lexiguard-32c63.firebasestorage.app',
    measurementId: 'G-CFS90X35FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl9R55zChTMVS0-4wQPxK-Z3rkp5PYkmk',
    appId: '1:398456425469:android:a642a2eba8dd14f06e2794',
    messagingSenderId: '398456425469',
    projectId: 'lexiguard-32c63',
    databaseURL: 'https://lexiguard-32c63-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lexiguard-32c63.firebasestorage.app',
  );
}
